@url = https://redesigned-space-giggle-wwqvrjqgjgrf995r-8080.app.github.dev/alunos

POST {{url}}
Content-Type: application/json

{
    "nome": "Nome3",
    "idade": 234
}

###

GET {{url}}

###

GET {{url}}/1

###

PUT {{url}}/1
Content-Type: application/json

{
    "nome": "Nome1",
    "idade": 19
}

###

DELETE {{url}}/2
