@url = https://redesigned-space-giggle-wwqvrjqgjgrf995r-8080.app.github.dev/alunos

POST {{url}}
Content-Type: application/json

{
    "nome": "Nome5",
    "idade": 17
}

###

GET {{url}}

###

GET {{url}}/1

###

PUT {{url}}/5
Content-Type: application/json

{
    "nome": "Nome5",
    "idade": 24
}

###

DELETE {{url}}/5
